### PR TITLE
fix issues and choose theme in setting

### PR DESCRIPTION
**Pull request by wiiznokes**

### CODE REVIEW

**Comment by wiiznokes** [comment]
Hi, 
I made some improvement on Android side :)

**Comment by teamclouday** [comment]
Cool, I'll take a look this weekend!

Also, somehow my Android Studio is broken that `liboboe.so` still cannot be compiled into the apk. If I downgrade Gradle then there will be lint errors in the editor.\
So I'm planning to modify `oboe` to use static builds which will use `git submodule`. Just FYI

**Comment by wiiznokes** [comment]
Ok, just for info, I use Dolphin 2021.3.1 Patch 1 as version for Android Studio.
The embedded JDK version 11.0.13.
Idk if you already try that but you should try to clean the project and rebuild.

**Comment by teamclouday** [comment]
> Ok, just for info, I use Dolphin 2021.3.1 Patch 1 as version for Android Studio.

Yep, I'm using the same version and it was a fresh reinstall. I've also tried cleaning the project and rebuilding.\
Anyway thanks for the info! I'll try to reinstall again and see if it works.

**Comment by teamclouday** [comment]
Hey I've tried the update and I really like the theme settings!👍\
Just curious, what does "Dynamic color (A12 and +)" mean? Is it for Samsung A12 or above only? (My phone is S8)

Btw, I fixed the `liboboe.so` build issue. It was because of `.gradle` path. It was initialized under the folder of my user name and there's a space in it. Guess Gradle wasn't smart enough to parse that😅. Now I'm able to use the same version and no need to change anything.

**Comment by wiiznokes** [comment]
> Just curious, what does "Dynamic color (A12 and +)" mean? Is it for Samsung A12 or above only? (My phone is S8)

No, it's just mean Android 12 and above. Maybe it will be better to clarify that in the app. It's an option to adjust the color of UI with the wallpaper or a color choose in system setting.

>Btw, I fixed the liboboe.so build issue.

Glad you finally success to fix that ahah

Also, I was able to build the Windows side with visual studio, (it's a real pain compare to Android studio I think), and I have some questions.
>Port all Windows code & dependencies to .Net Core (with [Avalonia](https://github.com/AvaloniaUI/Avalonia))

- What do you mean by Windows code ?
- Witch dependencies have to be port on .Net core ?
- Does the project use a version of .Net ? (When we use `using System;` for example, this library/namespace come from witch version of .Net?)
- Does this library can integrate with the project ? [LibUsbDotNet](https://github.com/LibUsbDotNet/LibUsbDotNet)

**Comment by teamclouday** [comment]
> It's an option to adjust the color of UI with the wallpaper or a color choose in system setting.

Sounds good, I'll merge this update.

> What do you mean by Windows code ?

It means the C# code dependent on Windows system.

> Witch dependencies have to be port on .Net core ?

So the Windows app is dependent on 4 parts:
* `VAC` or `VB-Audio` driver for sending audio from speaker to microphone (May need to find alternative drivers)
* `32feet.NET` for Bluetooth (It may be cross-platform already but I haven't tested it)
* `NAudio` for Audio playing (Not fully cross-platform as I'm aware of)
* `WPF` for UI (Already found `Avalonia` so it may be worth a try)

And C# is currently under .Net Framework. Need to port to .Net Core for cross-platform build.\
The main idea is that it might be cool to support multiple platforms (Personally want to support Linux). But it is huge work (re-write of almost everything) so please ignore it for now😂.

> Does the project use a version of .Net ? (When we use using System; for example, this library/namespace come from witch version of .Net?)

Yep, if you go to https://github.com/teamclouday/AndroidMic/blob/c107abe3164daeb6e999766d3a0375738d19e1f4/Windows/AndroidMic/AndroidMic.csproj#L11

You can see that it is using .Net Framework 4.7.2

> Does this library can integrate with the project ? [LibUsbDotNet](https://github.com/LibUsbDotNet/LibUsbDotNet)

You can try to search for it and install it by [NuGet Package Manager](https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio). This is how I installed other dependencies (i.e. 32feet, NAudio).\
From a quick look of the repo, it should be compatible with the project. Feel free to try it!

**Comment by teamclouday** [comment]
Merged

**Comment by wiiznokes** [comment]
Ok, thank for the response!

> VAC or VB-Audio driver for sending audio from speaker to microphone (May need to find alternative drivers)

I don't have an option to output the sound as an input on the pc, I don't know if it's normal but it would be useful for me.

>(Personally want to support Linux)

Me too👍

**Comment by teamclouday** [comment]
> I don't have an option to output the sound as an input on the pc, I don't know if it's normal but it would be useful for me.

Right, the current app is only able to play the audio data to a speaker. To use that audio as microphone input, we need a virtual microphone.\
There's a long story of how to create a virtual microphone on Windows, but the conclusion is that a Windows driver needs to be built to use a virtual microphone as input in all the other applications.\
Besides, the driver needs to be signed by public authorities to be installed on general user's machines.

Meanwhile, VAC or VB-Audio drivers can transmit speaker audio to a virtual microphone, and I'm currently using VB-Audio to forward the audio data to the virtual microphone.

On Linux though, it may be possible to try to find/develop a virtual microphone driver.

**Comment by wiiznokes** [comment]
> On Linux though, it may be possible to try to find/develop a virtual microphone driver.

Yes or just use this if the distrib use pipewire [pw-viz](https://github.com/Ax9D/pw-viz)

**Comment by teamclouday** [comment]
Thanks for sharing! I didn't know about this.\
I was still using PulseAudio. Will give it a try!

**Pull request merged**
