### PR TITLE
small fix

### PR DESCRIPTION
**Pull request by wiiznokes**
Hey, new update with small fixs, add icons and new name of package so lot of file have been changed.
I would like to support [Adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive), I think it's a good feature for Android 13 so please let me know where you found the app icon or just send it to me🙂

### CODE REVIEW

**Comment by teamclouday** [comment]
Cool! The image is from [here](https://pixabay.com/vectors/microphone-icon-logo-design-mic-3404243/), as documented in the README in the [Assets folder](https://github.com/teamclouday/AndroidMic/tree/main/Assets)

**Comment by wiiznokes** [comment]
Thanks! But I see this icon is monochromatic, I will need an xml icon to do this.
I can try to find it in the web, but if I fail can I use [this ](https://fonts.google.com/icons?icon.style=Outlined&icon.platform=android&icon.query=mic)instead ?

**Comment by teamclouday** [comment]
> I can try to find it in the web, but if I fail can I use [this ](https://fonts.google.com/icons?icon.style=Outlined&icon.platform=android&icon.query=mic)instead ?

Sure... Are you going to add white background color so that it won't go invisible?

> Maybe SVG will do the work, can you download it for me as you have an account

OK, here you go:\
microphone-3404243

**Comment by wiiznokes** [comment]
>Sure... Are you going to add white background color so that it won't go invisible?

I kinda prefer the current logo so I will found another solution. I will do it later I think, maybe recreate it with figma to see how it's work

**Pull request merged**
